services:
  postgres:
    image: pgvector/pgvector:pg16        # Postgres 16 with pgvector preinstalled
    container_name: imgsearcher-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: imgsearcher-adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pgdata:
